- name: get composer installer signature
  uri:
    url: https://composer.github.io/installer.sig
    return_content: true
  register: composer_installer_signature

- name: download composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    checksum: "sha384:{{ composer_installer_signature.content }}"

- name: run composer installer # noqa 301
  command: >
    php composer-installer.php
    chdir=/tmp

- name: move composer into globally-accessible location # noqa 301
  command: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer
