# Clone, build, and deploy, restarting caddy if necessary. This playbook must
# be run after provision and configure, and is used to deploy and build the
# specified commit (overridable via extra vars) on the server. Running this
# playbook in Vagrant will override the vagrant-link playbook, and vice-versa.

- hosts: all
  become: yes
  become_user: www-data
  roles:
    - deploy
  handlers:
    - include: roles/caddy/handlers/main.yml
