# handlers file for caddy
- name: restart caddy
  become: yes
  become_user: root
  service:
    name: caddy
    state: restarted

- name: restart php-fpm
  become: yes
  become_user: root
  service:
    name: php7.4-fpm
    state: restarted
