# All project build tasks go here. These tasks will only be run for the
# specified commit if the commit hasn't been deployed before or if "force"
# is true.

# install npm packages
# install composer packages

# Modify as-needed!

- name: install php modules
  composer:
    command: install
    working_dir: "{{ clone_path }}"

- name: install npm modules
  npm: path="{{ clone_path }}"

- name: build production version
  command: npm run build # noqa 301
  args:
    chdir: "{{ clone_path }}"
  environment:
    NODE_ENV: production

- name: generate build info file
  template: src=build_info.txt.j2 dest={{ clone_path }}/{{ build_info_path }}
  when: build_info_path is defined
