# Configure the box. This happens after the base initialization, but before
# the project is cloned or built.

- name: set hostname
  hostname: name={{ hostname }}

- name: ensure unattended upgrades are running
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Unattended-Upgrade "1";
    dest: /etc/apt/apt.conf.d/10periodic

- name: add loopback references to our domain in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "127.0.0.1 {{ hostname }} {{ site_fqdn }}"

- name: disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: restart sshd

- name: disallow challenge response authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"
  notify: restart sshd

- name: enable SSH forwarding for sudo
  lineinfile:
    dest: /etc/sudoers
    insertafter: '^#?\s*Defaults\s+env_keep\b'
    line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'

- include: git.yml
