# Add a user account for the currently logged-in user (development), otherwise
# add all users defined in group_vars/all (production).

- name: make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: allow 'wheel' group to have passwordless sudo
  copy:
    content: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/wheel_nopasswd
    mode: 0440

- include: localuser.yml
  when: env == "development"

- include: users.yml
  when: env != "development"
