title: Site

columns:
  - width: 1/1
    sections:
      folds: sections/folds
  - width: 1/2
    sections:
      contributors: sections/contributors
  - width: 1/2
    sections:
      pages:
        type: pages
        layout: list
        template:
          - page-blank
          - page-about
          - page-search
