title: Site

columns:
  - width: 1/1
    sections:
      folds: sections/folds
  - width: 1/2
    sections:
      contributors: sections/contributors
  - width: 1/2
    sections:
      pages:
        type: pages
        layout: list
        empty: No pages yet
        template:
          - page-blank
          - page-about
          - page-search
          - page-subscribe
      banners: sections/banners
      meta:
        type: fields
        fields:
          topics:
            label: Article Topics
            type: tags
            accept: all
          description:
            type: textarea
          # vendored on 1/5/22 by @s3ththompson
          # allowing only temporary redirect option, changing names
          # https://github.com/bnomei/kirby3-redirects/blob/master/blueprints/sections/redirects3xx.yml
          redirects:
            type: structure
            translate: false
            fields:
              fromuri:
                label: "From Path"
                help: "A relative path, e.g. /rsvp"
                type: text
                required: true
                before: paprikamagazine.com
              touri:
                label: "To URL"
                help: "An internal or external URL, e.g. https://google.com"
                type: text
                required: true
              code:
                label: "Status Code"
                default: "_302"
                type: select
                required: true
                options:
                  "_302": "302: Found"
      renderings: sections/site/renderings
