title: Site

columns:
  - width: 1/1
    sections:
      folds: sections/folds
  - width: 1/2
    sections:
      contributors: sections/contributors
  - width: 1/2
    sections:
      pages:
        type: pages
        layout: list
        empty: No pages yet
        template:
          - page-blank
          - page-about
          - page-search
          - page-subscribe
      banners: sections/banners
      meta:
        type: fields
        fields:
          topics:
            label: Article Topics
            type: tags
            accept: all
          description:
            type: textarea
      renderings: sections/site/renderings
